### ISSUE TITLE
MQTT error - SSL certificate not verified

### ISSUE THREAD

**Issue by ghost** [BananoCoin/boompow-legacy#27]
Since yesterday my boompow client stopped working. If i try to launch the bpow_client i get the following error:

MQTT connection failed: SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')
Connection failed: ConnectException(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))

The client is used on a windows 10 system.

Any idea how to fix this issue?

**Comment by bobvants** [comment]
In the folder where you have python installed, double click on `Install Certificates.command`

**Comment by uApiv** [comment]
> In the folder where you have python installed, double click on `Install Certificates.command`

I use anaconda, I can't_ find Install Certificates.command on Windows

**Comment by ghost** [comment]
> 
> 
> In the folder where you have python installed, double click on `Install Certificates.command`

Im sorry but there is no `Install Certificates.command` in my python folder. 
However, i found this [https://gist.github.com/marschhuynh/31c9375fc34a3e20c2d3b9eb8131d8f3](url) by searching the `Install Certificates.command`. I executed it and the boompow client is still not working... Though the [nano dpow client](https://github.com/guilhermelawless/nano-dpow) is not affected by this error and it is working fine the wholw time.

**Comment by glacierjl** [comment]
> In the folder where you have python installed, double click on `Install Certificates.command`

Are you sure you are mentioning Windows and not MacOS?

**Comment by ghost** [comment]
Hey all,
i forgot to give you an update on this issue.
In this case a fresh installation of windows was the (quickest) solution for my problem.

Thanks anyone for your input :)
