### ISSUE TITLE
Unhandled exception: 'Lock' object is not iterable

### ISSUE THREAD

**Issue by kbvaczi** [BananoCoin/boompow-legacy#8]
I get the following message when I try to run on Windows 10.

> Unhandled exception: 'Lock' object is not iterable
> Connection failed: TypeError("'Lock' object is not iterable")

Please advise.

**Comment by Goodzilla** [comment]
You're most likely running a higher version of Python (3.9.X) instead of the recommended 3.6.7. Downgrade to 3.6.7 and it should work fine.

**Comment by tststs** [comment]
using 3.8.8 on windows 10

**Comment by Unlifate** [comment]
Quick-Solution:

> pip3 uinstall hbmqtt
> pip3 install amqtt

You can now use python 3.9 for the boompow client!

Long term solution:
A dev should update the requirements.txt, because hbmqtt is deprecated.
also the application should check on startup if requirements are met (e.g. amqtt).

**Comment by bbedward** [comment]
[Released v3.0.1](https://github.com/BananoCoin/boompow/releases/tag/v3.0.1) with amqtt
